content: 
        "**There are no best or \"must pull\" options in Genshin.**
         \nNo number on a spreadsheet can say what \"best\" because the \"best\" character changes based on content and your own gameplay style. Properly built, every character can clear game content. As long as you enjoy the game you're winning."